name = "image-background-remover"
main = "src/index.js"
compatibility_date = "2023-08-01"
compatibility_flags = ["nodejs_compat"]

[vars]
REMOVE_BG_API_KEY = "YOUR_REMOVE_BG_API_KEY"

[[routes]]
pattern = "/*"
zone = "yourdomain.com"